### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by S4XXX** [bitowl/satisfactory-save-format#4]
For the purposes of an interactive map, I wondered how the notion of collected slugs was stored.

In fact objects disappear (linked entities too) and 2 strings are added at the end of the file, in what we could be called collectedObjects. This data is prefixed by an integer representing the number of pairs and followed by the pairs of strings themselves. Currently this data is fully part of the "missing" property contained in the "saveJson" object. Following your naming a pair is composed of "levelName" then "pathName".

We find in the majority of collectible items, such as nutbush, berrybush, mercerphere, slug ..

I hope this can help, I will PR if I have time

**Comment by S4XXX** [comment]
See PR https://github.com/bitowl/satisfactory-save-format/pull/5 :)

**Comment by bitowl** [comment]
Nice find. Thank you very much!
